### ISSUE TITLE
Incorrect dependancy

### ISSUE THREAD

**Issue by PSUdaemon** [piotrkowalczuk/promgrpc#7]
I'm new to go modules, but I think there might be a problem with this line in your `go.mod` file:
https://github.com/piotrkowalczuk/promgrpc/blob/master/v3/go.mod#L6

I think this conflicts with the package name and also with https://github.com/piotrkowalczuk/promgrpc/blob/master/v3/go.mod#L15

I have started getting the following error after importing your package and running `go get -u`:
`
go: github.com/grpc/grpc-go@v1.18.0: parsing go.mod: unexpected module path "google.golang.org/grpc"
`

I've confirmed that if I clone your repo and run `go mod tidy` in the `v3` directory it removes that line and then subsequent `go get -u` no longer return the error above.

**Comment by piotrkowalczuk** [comment]
@PSUdaemon thanks! I have to somehow automate running `go mod tidy` locally.

**Comment by PSUdaemon** [comment]
This fixed it. Thanks!
