### ISSUE TITLE
Opts to provide Tagging function

### ISSUE THREAD

**Issue by pacoguzman** [piotrkowalczuk/promgrpc#8]
Hi, I'm evaluating this library to use as base for RPC metrics in our services.

Maybe due to my limited knowledge of Go, I'm not able to find and easy way to change a little bit the metrics.

I'm interested in the `NewRequestDurationStatsHandler` but instead of using the label `clientUserAgent` we want to set up another label which value will be extracted in a similar way but from another metadata key.

To do that I want to populate the context in a similar way to [this](https://github.com/piotrkowalczuk/promgrpc/blob/308f5749a8ffe3aeab6159440e8888ad1cd2f18f/v4/stats_handler.go#L79-L83)

Would be possible to provide a function to do that as an option somewhere?

So later we can use the custom `rpcLabelFn` option to extract those values.

Thanks in advance.

I'm using v4 code

**Comment by piotrkowalczuk** [comment]
Hi @pacoguzman, thanks for being intrested to use this library! 

What you describe is achievable. The current design makes it possible but not very handy. You can achieve this by implementing your custom coordinator (like `StatsHandler`). This part can be easily implemented by applying [embedding](https://golang.org/doc/effective_go.html#embedding).

However, there is a problem with this approach. In your case, it means that you have to implement custom `HandleRPCLabelFunc` for every `StatsHandler` as well. 

I prepared smal PR #9 that I hope solves your problem. What do you think?

**Comment by pacoguzman** [comment]
Thanks for the quick response

> However, there is a problem with this approach. In your case, it means that you have to implement custom HandleRPCLabelFunc for every StatsHandler as well.

Sorry but I'm not following you about that. I guess that usually, we'll set up just one `promgrpc.StatsHandler` with one or more handlers. OK reading source again I guess the thing is that each of those handlers is a `stats.Handler` is that what you mean it?

So with #9 what we can do in each of those `stats.Handler` uses  `tagRPCLabelFn` for `TagRPC` and `handleRPCLabelFn` to provide labels for the metrics, isn't it?

I have a question isn't it better to populate the context via `func (h *StatsHandler) TagRPC` so later each `stats.Handler` receives the same ctx?

**Comment by pacoguzman** [comment]
Hi I've been trying to setup something and got the following

```go
package grpcs

import (
	"context"
	"strings"

	"google.golang.org/grpc/metadata"

	"github.com/piotrkowalczuk/promgrpc/v4"
	"github.com/prometheus/client_golang/prometheus"
	log "github.com/sirupsen/logrus"
	".../config"
	google "google.golang.org/grpc"
	"google.golang.org/grpc/stats"
	"google.golang.org/grpc/status"
)

func configurePrometheus(cfg *config.PrometheusConfig) google.ServerOption {
	if cfg.Enabled {
		log.Info("Configuring GRPC stats handler to register GRPC metrics")
		ssh := newServantStatsHandler()
		prometheus.MustRegister(ssh)
		return google.StatsHandler(ssh)
	}
	return &google.EmptyServerOption{}
}

var rpcLabelKey = 999

type rpcLabels struct {
	method               string
	service              string
	requestOriginService string
}

type servantStatsHandler struct {
	*promgrpc.StatsHandler
}

func newServantStatsHandler() *servantStatsHandler {
	sub := promgrpc.Server
	opts := []promgrpc.StatsHandlerOption{
		promgrpc.StatsHandlerWithHandleRPCLabelsFunc(handleRPCLabels),
	}

	return &servantStatsHandler{
		promgrpc.NewStatsHandler(
			promgrpc.NewRequestDurationStatsHandler(sub, incomingRequests, opts...),
		),
	}
}

// TagRPC implements stats Handler interface.
func (h *servantStatsHandler) TagRPC(ctx context.Context, inf *stats.RPCTagInfo) context.Context {
	service, method := split(inf.FullMethodName)

	return context.WithValue(ctx, rpcLabelKey, rpcLabels{
		service:              service,
		method:               method,
		requestOriginService: requestOriginService(ctx),
	})
}

func handleRPCLabels(ctx context.Context, stat stats.RPCStats) []string {
	l := ctx.Value(rpcLabelKey).(rpcLabels)
	return []string{
		l.method,
		l.service,
		status.Code(stat.(*stats.End).Error).String(),
		l.requestOriginService,
	}
}

var incomingRequests = prometheus.NewHistogramVec(
	prometheus.HistogramOpts{
		Name: "grpc_server_handled_requests",
		Help: "Incoming gRPC request time in seconds",
	},
	[]string{"method", "service", "code", "request_origin_service"},
)

func split(name string) (string, string) {
	if i := strings.LastIndex(name, "/"); i >= 0 {
		return name[1:i], name[i+1:]
	}
	return "unknown", "unknown"
}

const serviceMetadata = "x-service"

func requestOriginService(ctx context.Context) string {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		if sm, ok := md[serviceMetadata]; ok {
			return sm[0]
		}
	}
	return "unknown"
}
```

And I think this is flexible enough, we provide the metrics and how to put/retrieve labels on the ctx so those labels can be used for each of the stats handler we want to register in the future.

```go
NewRequestsInFlightStatsHandler
NewRequestDurationStatsHandler
NewResponsesTotalStatsHandler
NewMessagesReceivedTotalStatsHandler
NewMessagesSentTotalStatsHandler
NewMessageSentSizeStatsHandler
NewMessageReceivedSizeStatsHandler
```

The only one left is `NewConnectionsStatsHandler`.

what you did on #9 I think is helpful by the way, but not in our case.

Thanks for the help by the way.

**Comment by piotrkowalczuk** [comment]
@pacoguzman If performance penalty is not an issue in your case, this is precisely the way to go.
